export type Locale = "en" | "da";
const en = {
  nav: { services: "Services", whyWiCare: "Why WiCare", testimonials: "Testimonials", contact: "Contact", bookNow: "Book Now", getStarted: "Get Started", callUs: "+45 52 72 11 02" },
  hero: { badge: "Denmark's Premier Luxury Lifestyle Group", title: "Elite Home & Lifestyle Services", titleHighlight: "for Those Who Demand the Best", subtitle: "Discretion. Precision. Trust. One trusted partner managing every aspect of your home, lifestyle, and private residence. Executing your vision with flawless precision.", ctaConsultation: "Request a Consultation", ctaServices: "Our Services" },
  services: { sectionBadge: "Our Services", heading: "What We Offer", subheading: "Every service is defined based on your agreement. Choose what you need, nothing is pre-bundled.", flagship: "Flagship", extendsNote: "Extends to vehicle detailing, wardrobe care, ambient scenting, and device sanitization, all defined by your agreement.", learnMore: "Learn More", bookAny: "Book Any Service", cards: [{ subtitle: "Executive Home Cleaning", desc: "Premium cleaning for your home and workspace. White-glove service, carefully selected products, flexible scheduling." }, { subtitle: "Private Dining & Catering", desc: "13+ years Michelin-star expertise. Private chef dinners, corporate catering, exclusive events." }, { subtitle: "Property & Lifestyle Care", desc: "Gardening, construction, handyman services, pet care, and plant expertise. One trusted partner for everything." }] },
  trust: { badge: "Why Choose Us", heading: "The WiCare Difference", keyReasons: [{ title: "10+ Years", description: "Trusted by Copenhagen elite since 2016" }, { title: "100% Insured", description: "Full liability coverage for peace of mind" }, { title: "Background Checked", description: "Every team member vetted and trusted" }, { title: "White-Glove Service", description: "Premium standards on every visit" }] },
  whyUs: { badge: "The Difference", heading: "Why Discerning Clients Choose WiCare", subheading: "We are not a cleaning company. We are your trusted partner in maintaining the quality and elegance of your home or office.", ctaBook: "Book a Service", ctaCall: "Call +45 52 72 11 02" },
  testimonials: { badge: "Client Stories", heading: "What Our Clients Say", list: [{ name: "Sophie", profession: "Executive Director, Copenhagen", rating: 5, review: "WiCare has been looking after our penthouse for two years. The level of discretion and attention to detail is genuinely unmatched.", initials: "SA" }, { name: "Marcus", profession: "Expat & Property Owner", rating: 5, review: "Moving to Copenhagen with a family, I needed a cleaning team I could trust completely. WiCare deliver exactly what they promise: premium, reliable, and perfectly professional.", initials: "MV" }, { name: "Ingrid", profession: "Partner, Law Firm", rating: 5, review: "Our office has never looked better. The team is discreet, punctual, and thorough. The eco-friendly products were important to us. WiCare ticked every box.", initials: "IH" }, { name: "Thomas", profession: "Tech Entrepreneur", rating: 5, review: "I was sceptical about premium cleaning until WiCare. My villa has never been cleaner, and the team works around my busy schedule without any disruption.", initials: "TK" }, { name: "Camille", profession: "French Expat, Finance Director", rating: 5, review: "Three apartments managed, zero complaints. WiCare is the only team I trust with my properties.", initials: "CD" }, { name: "Henrik", profession: "Architect", rating: 5, review: "As someone obsessed with detail in my own work, I had very high standards. WiCare not only met them, they exceeded them.", initials: "HC" }], short: [{ profession: "Executive Director, Copenhagen", review: "Two years of impeccable service. Zero complaints. Best team in Copenhagen." }, { profession: "Property Owner", review: "The team delivers exactly what they promise. Premium, reliable, and perfectly professional." }, { profession: "Architect", review: "I had very high standards. WiCare not only met them, they exceeded them." }] },
  booking: { badge: "Book Now", heading: "Ready to Get Started?", subheading: "Call us today. We respond within 2 business hours.", stats: [{ number: "10+", label: "Years of Service", desc: "Trusted since 2016" }, { number: "100%", label: "Insured", desc: "Full coverage" }, { number: "2h", label: "Response Time", desc: "Always quick" }] },
  contact: { badge: "Contact", heading: "Get in Touch", intro: "We'd love to hear from you", introDesc: "Our team responds to every enquiry within 2 business hours.", phoneLabel: "Phone", emailLabel: "Email", locationLabel: "Location", location: "Copenhagen, Denmark", ctaCall: "Call Now", ctaEmail: "Send Email", directTitle: "Call Us Directly", directDesc: "Our team is ready to help. No forms, no waiting, just a conversation.", directAvailability: "Available 5 days a week. Response within 2 hours" },
  footer: { tagline: "Premium lifestyle services for private residences and professional environments across Copenhagen.", navTitle: "Navigate", contactTitle: "Contact", quickLinksTitle: "Quick Links", legalTitle: "Legal", bookNow: "Book Now", copyright: "© 2026 WiCare Cleaning ApS. All rights reserved.", privacy: "Privacy Policy", terms: "Terms of Service", links: [{ label: "Services", href: "/#services" }, { label: "Why WiCare", href: "/#trust" }, { label: "Testimonials", href: "/#testimonials" }, { label: "Book", href: "/#booking" }, { label: "Contact", href: "/#booking" }] },
  floating: { bookNow: "Book Now", ariaLabel: "Call WiCare" },
  servicePage: { included: "What's Included", whyChoose: "Why Choose", readyToBook: "Ready to Book?", callSchedulePre: "Call us to schedule your", callSchedulePost: "service.", backToServices: "Back to Services", alsoAvailable: "Also Available with WiClean", alsoDesc: "While your home is being serviced, your WiCare team can handle these additional services, tailored to your agreement, never pre-bundled.", bookToday: "Book", bookTodayDesc: "All services are defined based on your agreement. Choose what you need, nothing is pre-bundled. Call us to schedule your", bookTodayDescEnd: "service. We respond within 2 business hours.", viewAll: "View all WiCare services" },
  serviceDetail: {
    "wi-clean": { name: "WiClean", subtitle: "Executive Home Cleaning", longDescription: "WiClean is our flagship service, the foundation of the WiCare Group. We provide premium residential cleaning for CEOs, executives, and high-net-worth individuals across Copenhagen. Every detail is handled with discretion, precision, and an uncompromising commitment to quality. Our teams are fully insured, background-checked, and trained to a white-glove standard.", features: ["Private residences & estates", "CEO-ready workspaces", "White-glove finish", "Smart product selection", "Background-checked staff", "Fully insured"], details: ["Serving Copenhagen's most discerning clients since 2016", "Thoughtfully selected products balanced for safety and efficacy", "Flexible scheduling for mornings, evenings, weekends", "Dedicated team assigned to your property"] },
    "wi-cook": { name: "WiCook", subtitle: "Private Dining & Catering", longDescription: "WiCook brings Michelin-star and Danish Parliament culinary expertise directly to your home. Our chefs have cooked for heads of state, royalty, and the most demanding palates in Copenhagen. Whether it is an intimate dinner for two, a boardroom lunch, or a grand celebration, every dish is crafted with precision, creativity, and world-class technique.", features: ["Private chef dining", "Corporate catering", "Michelin pedigree", "Bespoke menus", "Wine pairing", "Event planning"], details: ["13+ years of Michelin-star and Danish Parliament experience", "Custom menu design for every occasion", "Ingredient sourcing from premium Danish purveyors", "Seamless setup, service, and cleanup"] },
    "wi-help": { name: "WiHelp", subtitle: "Premier Property & Lifestyle Care", longDescription: "WiHelp is your comprehensive solution for property and lifestyle needs. From expert landscaping and garden design to construction projects, handyman repairs, elite pet valet services, and specialized plant care. Our skilled professionals deliver the same standard of excellence that defines every WiCare brand. One trusted partner handles it all.", features: ["Landscaping & gardening", "Construction projects", "Handyman services", "Property maintenance", "Elite pet valet & walks", "Plant care & botanical expertise", "Leaf dusting & precision watering"], details: ["Vetted, licensed professionals for every service", "Full project management from concept to completion", "Expert plant care for luxury indoor greenery", "GPS-tracked pet walks with photo updates", "Transparent, fixed-price quotes"] }
  },
  legal: {
    privacy: { title: "Privacy Policy", updated: "Last updated: June 2026", sections: [
      { h: "1. Information We Collect", p: "We collect only the information necessary to provide our services: your name, contact details, address, and any preferences you share when booking. We do not collect sensitive personal data unless you provide it voluntarily." },
      { h: "2. How We Use Your Information", p: "Your information is used solely to schedule and deliver services, communicate with you, and improve our offering. We never sell or rent your personal data to third parties." },
      { h: "3. Data Storage & Security", p: "Client information is stored securely and accessed only by authorised WiCare personnel. We apply appropriate technical and organisational measures to protect your data." },
      { h: "4. Sharing of Information", p: "We never share personal data without your explicit consent, except where required by law. Our team members are bound by strict confidentiality obligations." },
      { h: "5. Your Rights", p: "Under GDPR you have the right to access, correct, or delete your personal data, and to withdraw consent at any time. Contact us to exercise these rights." },
      { h: "6. Contact", p: "For any privacy questions, contact WiCare Cleaning ApS, Copenhagen, Denmark. Phone: +45 52 72 11 02. Email: wicare.cleaning@gmail.com." }
    ] },
    terms: { title: "Terms of Service", updated: "Last updated: June 2026", sections: [
      { h: "1. Booking & Confirmation", p: "All services are booked via telephone at +45 52 72 11 02. A booking is confirmed once WiCare Group confirms availability. Services are subject to scheduler availability." },
      { h: "2. Pricing & Payment", p: "Prices are quoted per hour and may vary by service tier. Payment is due upon completion unless otherwise agreed in writing. WiCare Group accepts bank transfer and major credit cards." },
      { h: "3. Cancellation Policy", p: "Cancellations made less than 24 hours before the scheduled appointment may incur a fee of 50% of the estimated service value. WiCare Group reserves the right to cancel or reschedule due to unforeseen circumstances." },
      { h: "4. Liability", p: "WiCare Group carries professional liability insurance. Clients are responsible for securing valuable items prior to service. WiCare Group is not liable for pre-existing damage or wear and tear." },
      { h: "5. Privacy", p: "Client information is handled in accordance with our Privacy Policy. We never share personal data without explicit consent." },
      { h: "6. Amendments", p: "WiCare Group reserves the right to amend these terms at any time. Clients will be notified of material changes." },
      { h: "Contact", p: "WiCare Cleaning ApS, Copenhagen, Denmark. Phone: +45 52 72 11 02. Email: wicare.cleaning@gmail.com." }
    ] }
  }
};
const da: typeof en = {
  nav: { services: "Services", whyWiCare: "Hvorfor WiCare", testimonials: "Udtalelser", contact: "Kontakt", bookNow: "Book Nu", getStarted: "Kom i Gang", callUs: "+45 52 72 11 02" },
  hero: { badge: "Danmarks Førende Luksus Livsstilsgruppe", title: "Elite Hjem & Livsstilsservices", titleHighlight: "for Dem, Der Forventer det Bedste", subtitle: "Diskretion. Præcision. Tillid. Én betroet partner, der styrer alle aspekter af dit hjem, din livsstil og din private bolig. Vi udfører din vision med fejlfri præcision.", ctaConsultation: "Anmod om Konsultation", ctaServices: "Vores Services" },
  services: { sectionBadge: "Vores Services", heading: "Hvad Vi Tilbyder", subheading: "Hver service defineres baseret på din aftale. Vælg hvad du har brug for, intet er forudbestemt.", flagship: "Flagskib", extendsNote: "Omfatter også bilpleje, garderobepleje, duftservice og rengøring af elektronik, alt defineret i din aftale.", learnMore: "Læs Mere", bookAny: "Bestil Enhver Service", cards: [{ subtitle: "Eksklusiv Hjemmerengøring", desc: "Premium rengøring til dit hjem og din arbejdsplads. White-glove service, omhyggeligt udvalgte produkter, fleksibel planlægning." }, { subtitle: "Privat Madlavning & Catering", desc: "13+ års Michelin-stjerne ekspertise. Private kokmiddage, firmacatering, eksklusive events." }, { subtitle: "Ejendoms- & Livsstilspleje", desc: "Havearbejde, byggeri, handyman-service, kæledyrspleje og planteekspertise. Én betroet partner til det hele." }] },
  trust: { badge: "Hvorfor Vælge Os", heading: "WiCare Forskellen", keyReasons: [{ title: "10+ År", description: "Betroet af Københavns elite siden 2016" }, { title: "100% Forsikret", description: "Fuld ansvarsdækning for ro i sindet" }, { title: "Baggrundstjekket", description: "Hvert teammedlem er godkendt og betroet" }, { title: "White-Glove Service", description: "Premium standarder ved hvert besøg" }] },
  whyUs: { badge: "Forskellen", heading: "Hvorfor Kræsne Kunder Vælger WiCare", subheading: "Vi er ikke et rengøringsfirma. Vi er din betroede partner i at opretholde kvaliteten og elegancen i dit hjem eller kontor.", ctaBook: "Bestil en Service", ctaCall: "Ring +45 52 72 11 02" },
  testimonials: { badge: "Kundehistorier", heading: "Hvad Vores Kunder Siger", list: [{ name: "Sophie", profession: "Executive Director, København", rating: 5, review: "WiCare har passet vores penthouse i to år. Niveauet af diskretion og opmærksomhed på detaljer er virkelig uovertruffent.", initials: "SA" }, { name: "Marcus", profession: "Ekspat & Ejendomsejer", rating: 5, review: "Da jeg flyttede til København med familie, havde jeg brug for et rengøringsteam, jeg kunne stole fuldstændigt på. WiCare leverer præcis, hvad de lover: premium, pålideligt og perfekt professionelt.", initials: "MV" }, { name: "Ingrid", profession: "Partner, Advokatfirma", rating: 5, review: "Vores kontor har aldrig set bedre ud. Teamet er diskret, punktligt og grundigt. De miljøvenlige produkter var vigtige for os. WiCare opfyldte alle krav.", initials: "IH" }, { name: "Thomas", profession: "Tech Iværksætter", rating: 5, review: "Jeg var skeptisk over for premium rengøring indtil WiCare. Min villa har aldrig været renere, og teamet arbejder omkring min travle tidsplan uden nogen forstyrrelse.", initials: "TK" }, { name: "Camille", profession: "Fransk Ekspat, Finansdirektør", rating: 5, review: "Tre lejligheder administreret, nul klager. WiCare er det eneste team, jeg stoler på med mine ejendomme.", initials: "CD" }, { name: "Henrik", profession: "Arkitekt", rating: 5, review: "Som en, der er besat af detaljer i mit eget arbejde, havde jeg meget høje standarder. WiCare opfyldte dem ikke kun, de overgik dem.", initials: "HC" }], short: [{ profession: "Executive Director, København", review: "To års upåklagelig service. Nul klager. Det bedste team i København." }, { profession: "Ejendomsejer", review: "Teamet leverer præcis, hvad de lover. Premium, pålideligt og perfekt professionelt." }, { profession: "Arkitekt", review: "Jeg havde meget høje standarder. WiCare opfyldte dem ikke kun, de overgik dem." }] },
  booking: { badge: "Book Nu", heading: "Klar til at Komme i Gang?", subheading: "Ring til os i dag. Vi svarer inden for 2 arbejdstimer.", stats: [{ number: "10+", label: "Års Service", desc: "Betroet siden 2016" }, { number: "100%", label: "Forsikret", desc: "Fuld dækning" }, { number: "2t", label: "Svartid", desc: "Altid hurtigt" }] },
  contact: { badge: "Kontakt", heading: "Kom i Kontakt", intro: "Vi vil gerne høre fra dig", introDesc: "Vores team svarer på alle henvendelser inden for 2 arbejdstimer.", phoneLabel: "Telefon", emailLabel: "Email", locationLabel: "Beliggenhed", location: "København, Danmark", ctaCall: "Ring Nu", ctaEmail: "Send Email", directTitle: "Ring til Os Direkte", directDesc: "Vores team er klar til at hjælpe. Ingen formularer, ingen ventetid, bare en samtale.", directAvailability: "Tilgængelig 5 dage om ugen. Svar inden for 2 timer" },
  footer: { tagline: "Premium livsstilsservices til private boliger og professionelle miljøer i hele København.", navTitle: "Navigation", contactTitle: "Kontakt", quickLinksTitle: "Hurtige Links", legalTitle: "Juridisk", bookNow: "Book Nu", copyright: "© 2026 WiCare Cleaning ApS. Alle rettigheder forbeholdes.", privacy: "Privatlivspolitik", terms: "Servicevilkår", links: [{ label: "Services", href: "/#services" }, { label: "Hvorfor WiCare", href: "/#trust" }, { label: "Udtalelser", href: "/#testimonials" }, { label: "Book", href: "/#booking" }, { label: "Kontakt", href: "/#booking" }] },
  floating: { bookNow: "Book Nu", ariaLabel: "Ring til WiCare" },
  servicePage: { included: "Hvad Er Inkluderet", whyChoose: "Hvorfor Vælge", readyToBook: "Klar til at Booke?", callSchedulePre: "Ring til os for at planlægge din", callSchedulePost: "service.", backToServices: "Tilbage til Services", alsoAvailable: "Også Tilgængelig med WiClean", alsoDesc: "Mens dit hjem bliver serviceret, kan dit WiCare-team håndtere disse ekstra services, skræddersyet til din aftale, aldrig forudbestemt.", bookToday: "Bestil", bookTodayDesc: "Alle services defineres baseret på din aftale. Vælg hvad du har brug for, intet er forudbestemt. Ring til os for at planlægge din", bookTodayDescEnd: "service. Vi svarer inden for 2 arbejdstimer.", viewAll: "Se alle WiCare services" },
  serviceDetail: {
    "wi-clean": { name: "WiClean", subtitle: "Eksklusiv Hjemmerengøring", longDescription: "WiClean er vores flagskibsservice og fundamentet for WiCare Group. Vi leverer premium boligrengøring til direktører, ledere og personer med høj nettoformue i hele København. Hver detalje håndteres med diskretion, præcision og en kompromisløs forpligtelse til kvalitet. Vores teams er fuldt forsikrede, baggrundstjekkede og trænet til en white-glove standard.", features: ["Private boliger & ejendomme", "Direktørklare arbejdspladser", "White-glove finish", "Smart produktvalg", "Baggrundstjekket personale", "Fuldt forsikret"], details: ["Betjener Københavns mest kræsne kunder siden 2016", "Omhyggeligt udvalgte produkter balanceret for sikkerhed og effektivitet", "Fleksibel planlægning til morgener, aftener og weekender", "Dedikeret team tildelt din ejendom"] },
    "wi-cook": { name: "WiCook", subtitle: "Privat Madlavning & Catering", longDescription: "WiCook bringer kulinarisk ekspertise fra Michelin-restauranter og Folketinget direkte til dit hjem. Vores kokke har lavet mad for statsoverhoveder, kongelige og de mest krævende ganer i København. Uanset om det er en intim middag for to, en frokost i bestyrelseslokalet eller en stor fejring, tilberedes hver ret med præcision, kreativitet og teknik i verdensklasse.", features: ["Privat kokmiddag", "Erhvervscatering", "Michelin-baggrund", "Skræddersyede menuer", "Vinmenu", "Eventplanlægning"], details: ["13+ års erfaring fra Michelin-restauranter og Folketinget", "Skræddersyet menudesign til enhver lejlighed", "Råvarer fra førende danske leverandører", "Problemfri opdækning, servering og oprydning"] },
    "wi-help": { name: "WiHelp", subtitle: "Førende Ejendoms- & Livsstilspleje", longDescription: "WiHelp er din samlede løsning til ejendoms- og livsstilsbehov. Fra ekspert-landskabspleje og havedesign til byggeprojekter, handyman-reparationer, eksklusiv kæledyrsservice og specialiseret plantepleje. Vores dygtige fagfolk leverer den samme høje standard, der definerer alle WiCare-brands. Én betroet partner klarer det hele.", features: ["Landskabspleje & havearbejde", "Byggeprojekter", "Handyman-service", "Ejendomsvedligeholdelse", "Eksklusiv kæledyrspasning & gåture", "Plantepleje & botanisk ekspertise", "Bladafstøvning & præcisionsvanding"], details: ["Godkendte, autoriserede fagfolk til hver service", "Fuld projektledelse fra idé til færdiggørelse", "Ekspert plantepleje til luksus indendørs grønt", "GPS-sporede gåture med fotoopdateringer", "Gennemsigtige tilbud til fast pris"] }
  },
  legal: {
    privacy: { title: "Privatlivspolitik", updated: "Senest opdateret: juni 2026", sections: [
      { h: "1. Oplysninger Vi Indsamler", p: "Vi indsamler kun de oplysninger, der er nødvendige for at levere vores services: dit navn, kontaktoplysninger, adresse og eventuelle præferencer, du deler ved booking. Vi indsamler ikke følsomme personoplysninger, medmindre du afgiver dem frivilligt." },
      { h: "2. Hvordan Vi Bruger Dine Oplysninger", p: "Dine oplysninger bruges udelukkende til at planlægge og levere services, kommunikere med dig og forbedre vores tilbud. Vi sælger eller udlejer aldrig dine personoplysninger til tredjeparter." },
      { h: "3. Datalagring & Sikkerhed", p: "Kundeoplysninger opbevares sikkert og tilgås kun af autoriseret WiCare-personale. Vi anvender passende tekniske og organisatoriske foranstaltninger for at beskytte dine data." },
      { h: "4. Deling af Oplysninger", p: "Vi deler aldrig personoplysninger uden dit udtrykkelige samtykke, undtagen hvor loven kræver det. Vores medarbejdere er bundet af strenge fortrolighedsforpligtelser." },
      { h: "5. Dine Rettigheder", p: "I henhold til GDPR har du ret til at få adgang til, rette eller slette dine personoplysninger og til at trække dit samtykke tilbage til enhver tid. Kontakt os for at udøve disse rettigheder." },
      { h: "6. Kontakt", p: "For spørgsmål om privatliv, kontakt WiCare Cleaning ApS, København, Danmark. Telefon: +45 52 72 11 02. Email: wicare.cleaning@gmail.com." }
    ] },
    terms: { title: "Servicevilkår", updated: "Senest opdateret: juni 2026", sections: [
      { h: "1. Booking & Bekræftelse", p: "Alle services bookes telefonisk på +45 52 72 11 02. En booking bekræftes, når WiCare Group bekræfter tilgængelighed. Services er underlagt planlæggerens tilgængelighed." },
      { h: "2. Priser & Betaling", p: "Priser oplyses pr. time og kan variere efter serviceniveau. Betaling forfalder ved færdiggørelse, medmindre andet er skriftligt aftalt. WiCare Group accepterer bankoverførsel og større kreditkort." },
      { h: "3. Afbestillingspolitik", p: "Afbestillinger foretaget mindre end 24 timer før den planlagte aftale kan medføre et gebyr på 50% af den anslåede serviceværdi. WiCare Group forbeholder sig retten til at aflyse eller omlægge på grund af uforudsete omstændigheder." },
      { h: "4. Ansvar", p: "WiCare Group har en erhvervsansvarsforsikring. Kunder er ansvarlige for at sikre værdigenstande inden service. WiCare Group er ikke ansvarlig for eksisterende skader eller almindeligt slid." },
      { h: "5. Privatliv", p: "Kundeoplysninger håndteres i overensstemmelse med vores Privatlivspolitik. Vi deler aldrig personoplysninger uden udtrykkeligt samtykke." },
      { h: "6. Ændringer", p: "WiCare Group forbeholder sig retten til at ændre disse vilkår til enhver tid. Kunder vil blive underrettet om væsentlige ændringer." },
      { h: "Kontakt", p: "WiCare Cleaning ApS, København, Danmark. Telefon: +45 52 72 11 02. Email: wicare.cleaning@gmail.com." }
    ] }
  }
};
export const translations = { en, da };
