export type Locale = "en" | "da";
const en = {
  nav: { services: "Services", whyWiCare: "Why WiCare", testimonials: "Testimonials", contact: "Contact", bookNow: "Book Now", getStarted: "Get Started", callUs: "+45 52 72 11 02" },
  hero: { badge: "Denmark's Premier Luxury Lifestyle Group", title: "Elite Home & Lifestyle Services", titleHighlight: "for Those Who Demand the Best", subtitle: "Discretion. Precision. Trust. One trusted partner managing every aspect of your home, lifestyle, and private residence — executing your vision with flawless precision.", ctaConsultation: "Request a Consultation", ctaServices: "Our Services" },
  services: { sectionBadge: "Our Services", heading: "Everything We Offer", subheading: "Every service is defined based on your agreement. Choose what you need — nothing is pre-bundled.", flagship: "Flagship", extendsNote: "Extends to vehicle detailing, wardrobe care, ambient scenting, and device sanitization — all defined by your agreement.", learnMore: "Learn More", bookAny: "Book Any Service" },
  trust: { badge: "Why Clients Choose Us", heading: "The WiCare Standard", items: [{ label: "10+ Years Experience", desc: "A decade of premium service" }, { label: "100% Insured", desc: "Full liability coverage" }, { label: "Smart Product Selection", desc: "Balanced for safety & efficacy" }, { label: "Background Checked", desc: "Vetted & trusted staff" }, { label: "Reliable Scheduling", desc: "Always on time" }, { label: "Premium Service", desc: "White-glove standard" }] },
  whyUs: { badge: "The Difference", heading: "Why Discerning Clients Choose WiCare", subheading: "We are not a cleaning company. We are your trusted partner in maintaining the quality and elegance of your home or office.", ctaBook: "Book a Service", ctaCall: "Call +45 52 72 11 02" },
  testimonials: { badge: "Client Stories", heading: "What Our Clients Say", list: [{ name: "Sophie", profession: "Executive Director, Copenhagen", rating: 5, review: "WiCare has been looking after our penthouse for two years. The level of discretion and attention to detail is genuinely unmatched.", initials: "SA" }, { name: "Marcus", profession: "Expat & Property Owner", rating: 5, review: "Moving to Copenhagen with a family, I needed a cleaning team I could trust completely. WiCare deliver exactly what they promise: premium, reliable, and perfectly professional.", initials: "MV" }, { name: "Ingrid", profession: "Partner, Law Firm", rating: 5, review: "Our office has never looked better. The team is discreet, punctual, and thorough. The eco-friendly products were important to us — WiCare ticked every box.", initials: "IH" }, { name: "Thomas", profession: "Tech Entrepreneur", rating: 5, review: "I was sceptical about premium cleaning — until WiCare. My villa has never been cleaner, and the team works around my busy schedule without any disruption.", initials: "TK" }, { name: "Camille", profession: "French Expat, Finance Director", rating: 5, review: "Three apartments managed, zero complaints. WiCare is the only team I trust with my properties.", initials: "CD" }, { name: "Henrik", profession: "Architect", rating: 5, review: "As someone obsessed with detail in my own work, I had very high standards. WiCare not only met them — they exceeded them.", initials: "HC" }] },
  booking: { badge: "Book Now", heading: "Ready to Experience WiCare?", subheading: "Call us today to schedule any of our comprehensive services. We answer within 2 business hours.", stats: [{ number: "7+", label: "Premium Services", desc: "From cleaning to property care" }, { number: "10+", label: "Years Experience", desc: "Serving Copenhagen elite" }, { number: "2h", label: "Response Time", desc: "Fast, personal service" }] },
  contact: { badge: "Contact", heading: "Get in Touch", intro: "We'd love to hear from you", introDesc: "Our team responds to every enquiry within 2 business hours.", phoneLabel: "Phone", emailLabel: "Email", locationLabel: "Location", location: "Copenhagen, Denmark", ctaCall: "Call Now", ctaEmail: "Send Email", directTitle: "Call Us Directly", directDesc: "Our team is ready to help. No forms, no waiting — just a conversation.", directAvailability: "Available 7 days a week · Response within 2 hours" },
  footer: { tagline: "Premium lifestyle services for private residences and professional environments across Copenhagen.", navTitle: "Navigate", contactTitle: "Contact", copyright: "© 2026 WiCare Cleaning ApS. All rights reserved.", privacy: "Privacy Policy", terms: "Terms of Service", links: [{ label: "Services", href: "/#services" }, { label: "Why WiCare", href: "/#why-us" }, { label: "Testimonials", href: "/#testimonials" }, { label: "Book", href: "/#booking" }, { label: "Contact", href: "/#contact" }] },
  floating: { bookNow: "Book Now", ariaLabel: "Call WiCare" },
  servicePage: { included: "What's Included", whyChoose: "Why Choose", alsoAvailable: "Also Available with WiClean", alsoDesc: "While your home is being serviced, your WiCare team can handle these additional services — tailored to your agreement, never pre-bundled.", bookToday: "Book", bookTodayDesc: "All services are defined based on your agreement — choose what you need, nothing is pre-bundled. Call us to schedule your", bookTodayDescEnd: "service. We respond within 2 business hours.", viewAll: "View all WiCare services" }
};
const da: typeof en = {
  nav: { services: "Services", whyWiCare: "Hvorfor WiCare", testimonials: "Udtalelser", contact: "Kontakt", bookNow: "Book Nu", getStarted: "Kom i Gang", callUs: "+45 52 72 11 02" },
  hero: { badge: "Danmarks Førende Luksus Livsstilsgruppe", title: "Elite Hjem & Livsstilsservices", titleHighlight: "for Dem, Der Forventer det Bedste", subtitle: "Diskretion. Præcision. Tillid. En betroet partner, der styrer alle aspekter af dit hjem, din livsstil og din private bolig — udføre din vision med fejlfri præcision.", ctaConsultation: "Anmod om Konsultation", ctaServices: "Vores Services" },
  services: { sectionBadge: "Vores Services", heading: "Alt, Vi Tilbyder", subheading: "Hver service defineres baseret på din aftale. Vælg hvad du har brug for — intet er forudbestemt.", flagship: "Flagskib", extendsNote: "Omfatter også bilpleje, garderobepleje, duftservice og rengøring af elektronik — alt defineret i din aftale.", learnMore: "Læs Mere", bookAny: "Bestil Enhver Service" },
  trust: { badge: "Hvorfor Kunder Vælger Os", heading: "WiCare Standarden", items: [{ label: "10+ Års Erfaring", desc: "Et årti med premium service" }, { label: "100% Forsikret", desc: "Fuld ansvarsdækning" }, { label: "Smart Produktvalg", desc: "Balanceret for sikkerhed & effektivitet" }, { label: "Baggrundstjekket", desc: "Godkendt & betroet personale" }, { label: "Pålidelig Planlægning", desc: "Altid til tiden" }, { label: "Premium Service", desc: "White-glove standard" }] },
  whyUs: { badge: "Forskellen", heading: "Hvorfor Kræsne Kunder Vælger WiCare", subheading: "Vi er ikke et rengøringsfirma. Vi er din betroede partner i at opretholde kvaliteten og elegansen i dit hjem eller kontor.", ctaBook: "Bestil en Service", ctaCall: "Ring +45 52 72 11 02" },
  testimonials: { badge: "Kundehistorier", heading: "Hvad Vores Kunder Siger", list: [{ name: "Sophie", profession: "Executive Director, København", rating: 5, review: "WiCare har passet vores penthouse i to år. Niveauet af diskretion og opmærksomhed på detaljer er virkelig uovertruffent.", initials: "SA" }, { name: "Marcus", profession: "Ekspat & Ejendomsejer", rating: 5, review: "Da jeg flyttede til København med familie, havde jeg brug for et rengøringsteam, jeg kunne stole fuldstændigt på. WiCare leverer præcis, hvad de lover: premium, pålideligt og perfekt professionelt.", initials: "MV" }, { name: "Ingrid", profession: "Partner, Advokatfirma", rating: 5, review: "Vores kontor har aldrig set bedre ud. Teamet er diskret, punktligt og grundigt. De miljøvenlige produkter var vigtige for os — WiCare opfyldte alle krav.", initials: "IH" }, { name: "Thomas", profession: "Tech Iværksætter", rating: 5, review: "Jeg var skeptisk over for premium rengøring — indtil WiCare. Min villa har aldrig været renere, og teamet arbejder omkring min travle tidsplan uden nogen forstyrrelse.", initials: "TK" }, { name: "Camille", profession: "Fransk Ekspat, Finansdirektør", rating: 5, review: "Tre lejligheder administreret, nul klager. WiCare er det eneste team, jeg stoler på med mine ejendomme.", initials: "CD" }, { name: "Henrik", profession: "Arkitekt", rating: 5, review: "Som en, der er besat af detaljer i mit eget arbejde, havde jeg meget høje standarder. WiCare opfyldte dem ikke kun — de overgik dem.", initials: "HC" }] },
  booking: { badge: "Book Nu", heading: "Klar til at Opleve WiCare?", subheading: "Ring til os i dag for at planlægge en af vores omfattende services. Vi svarer inden for 2 arbejdstimer.", stats: [{ number: "7+", label: "Premium Services", desc: "Fra rengøring til ejendomspleje" }, { number: "10+", label: "Års Erfaring", desc: "Serverer Københavns elite" }, { number: "2t", label: "Svartid", desc: "Hurtig, personlig service" }] },
  contact: { badge: "Kontakt", heading: "Kom i Kontakt", intro: "Vi vil gerne høre fra dig", introDesc: "Vores team svarer på alle henvendelser inden for 2 arbejdstimer.", phoneLabel: "Telefon", emailLabel: "Email", locationLabel: "Beliggenhed", location: "København, Danmark", ctaCall: "Ring Nu", ctaEmail: "Send Email", directTitle: "Ring til Os Direkte", directDesc: "Vores team er klar til at hjælpe. Ingen formularer, ingen ventetid — bare en samtale.", directAvailability: "Tilgængelig 7 dage om ugen · Svar inden for 2 timer" },
  footer: { tagline: "Premium livsstilsservices til private boliger og professionelle miljøer i hele København.", navTitle: "Navigation", contactTitle: "Kontakt", copyright: "© 2026 WiCare Cleaning ApS. Alle rettigheder forbeholdes.", privacy: "Privatlivspolitik", terms: "Servicevilkår", links: [{ label: "Services", href: "/#services" }, { label: "Hvorfor WiCare", href: "/#why-us" }, { label: "Udtalelser", href: "/#testimonials" }, { label: "Book", href: "/#booking" }, { label: "Kontakt", href: "/#contact" }] },
  floating: { bookNow: "Book Nu", ariaLabel: "Ring til WiCare" },
  servicePage: { included: "Hvad Er Inkluderet", whyChoose: "Hvorfor Vælge", alsoAvailable: "Også Tilgængelig med WiClean", alsoDesc: "Mens dit hjem bliver serviceret, kan dit WiCare-team håndtere disse ekstra services — skræddersyet til din aftale, aldrig forudbestemt.", bookToday: "Bestil", bookTodayDesc: "Alle services defineres baseret på din aftale — vælg hvad du har brug for, intet er forudbestemt. Ring til os for at planlægge din", bookTodayDescEnd: "service. Vi svarer inden for 2 arbejdstimer.", viewAll: "Se alle WiCare services" }
};
export const translations = { en, da };
