export type Locale = "en" | "da";
const en = {
  nav: { services: "Services", whyWiCare: "Why WiCare", business: "Business", testimonials: "Testimonials", contact: "Contact", bookNow: "Book Now", getStarted: "Call Us", callUs: "+45 52 72 11 02" },
  hero: { badge: "North Copenhagen", title: "VIP\nHome & Lifestyle\nServices", motto: "Discretion. Precision. Trust.", subtitle: "One trusted partner for every aspect of your home, your lifestyle and your business.\nExecuting your vision with flawless precision.", ctaConsultation: "Request a Consultation", ctaServices: "Our Services", callCta: "Call" },
  services: { sectionBadge: "Our Services", heading: "What We Offer", subheading: "Every service is defined based on your agreement. Choose what you need, nothing is pre-bundled.", flagship: "Flagship", extendsNote: "Extends to vehicle detailing, wardrobe care, ambient scenting, and device sanitization, all defined by your agreement.", learnMore: "Learn More", bookAny: "Book Any Service", cards: [{ subtitle: "Home Cleaning", desc: "VIP cleaning for your home and workspace. White-glove service, carefully selected products, flexible scheduling." }, { subtitle: "Private Dining & Catering", desc: "Experienced chefs for private dinners, corporate catering, and exclusive events." }, { subtitle: "Property & Garden Care", desc: "Gardening, construction, handyman services, dog walking, and watering plants.\nOne trusted partner for everything." }] },
  whyUs: { badge: "The Difference", heading: "Why Discerning Clients Choose WiCare", subheading: "We are not a cleaning company. We are your trusted partner in maintaining the quality and elegance of your home or office.", ctaBook: "Book a Service", ctaCall: "Call +45 52 72 11 02" },
  booking: { badge: "Book Now", heading: "Ready to Get Started?", subheading: "Call us today. We respond within 2 business hours.", note: "Please store cash, jewellery and other valuables in a secure place before your appointment.", or: "Or write to us", whatsapp: "WhatsApp", email: "Email", stepsTitle: "How it works", steps: [{ title: "Call us", desc: "Tell us what you need, for your home or your business." }, { title: "We agree the details", desc: "Scope, timing and price are agreed with you. No fixed packages." }, { title: "Your dedicated team", desc: "The same discreet, punctual team from the very first visit." }] },
  contact: { badge: "Contact", heading: "Get in Touch", intro: "We'd love to hear from you", introDesc: "Our team responds to every enquiry within 2 business hours.", phoneLabel: "Phone", emailLabel: "Email", locationLabel: "Service Area", location: "Northern Suburbs of Copenhagen", ctaCall: "Call Now", ctaEmail: "Send Email", directTitle: "Call Us Directly", directDesc: "Our team is ready to help. No forms, no waiting, just a conversation.", directAvailability: "Available 5 days a week. Response within 2 hours" },
  areasMap: { badge: "Areas", heading: "Where we work", lede: "The northern suburbs of Copenhagen, from Hellerup to Hørsholm. For private homes and businesses alike.", note: "Illustrative map", mapLabel: "Map of the areas WiCare serves north of Copenhagen", south: "Copenhagen" },
  footer: { tagline: "VIP lifestyle services for private residences and professional environments across the northern suburbs of Copenhagen.", navTitle: "Navigate", contactTitle: "Contact", quickLinksTitle: "Quick Links", legalTitle: "Legal", bookNow: "Book Now", areasTitle: "Areas We Serve", areas: "Hellerup · Charlottenlund · Klampenborg · Gentofte · Rudersdal\nHørsholm · Rungsted · Vedbæk · Skodsborg · North Copenhagen", cvr: "CVR-nummer: 46213270", copyright: "© 2026 WiCare ApS. All rights reserved.", privacy: "Privacy Policy", terms: "Terms of Service", links: [{ label: "Services", href: "/#services" }, { label: "Why WiCare", href: "/#trust" }, { label: "Testimonials", href: "/#testimonials" }, { label: "Book", href: "/#book" }, { label: "Contact", href: "/#book" }] },
  floating: { bookNow: "Book Now", ariaLabel: "Call WiCare", whatsappAria: "Chat on WhatsApp", whatsappMsg: "Hi WiCare, I'd like to ask about your services." },
  notFound: { title: "Page Not Found", desc: "Sorry, the page you are looking for does not exist or has moved.", home: "Back to Home" },
  consent: { text: "We use cookies to measure traffic and improve your experience. You can accept or decline non-essential cookies.", accept: "Accept", decline: "Decline", privacy: "Privacy Policy" },
  faq: { badge: "FAQ", nav: "FAQ", heading: "Frequently Asked Questions", intro: "Answers to common questions about WiCare's VIP home and lifestyle services in the northern suburbs of Copenhagen.", items: [
    { q: "Which areas do you serve?", a: "We serve private homes and businesses across the northern suburbs of Copenhagen — Gentofte (Hellerup, Skovshoved, Charlottenlund, Ordrup, Klampenborg, Jægersborg), Lyngby-Taarbæk (Kongens Lyngby, Sorgenfri, Virum, Taarbæk), Rudersdal (Holte, Søllerød, Nærum, Skodsborg, Vedbæk, Birkerød), Hørsholm, Rungsted and Allerød." },
    { q: "What services do you offer?", a: "Three: Home Cleaning, Private Dining & Catering, and Property & Garden Care — each tailored to your agreement, never pre-bundled." },
    { q: "Are your staff vetted and background-checked?", a: "Yes. Every team member is background-checked, trained to a white-glove standard, and bound to discretion and confidentiality." },
    { q: "How do I request a quote or booking?", a: "Call us on +45 52 72 11 02, or message us on WhatsApp or by email. We respond within two business hours, and we always agree the scope and price with you before we start." },
    { q: "Do you offer recurring and one-off services?", a: "Both. We arrange regular schedules or single visits, defined around your needs." },
    { q: "How do you handle keys, privacy and valuables?", a: "We handle keys and access securely and treat your home with discretion. We ask that you store cash, jewellery and valuables before each visit." },
    { q: "What are your opening hours?", a: "Monday to Friday, 08:00–18:00, with flexible scheduling for mornings, evenings and weekends by arrangement." },
  ] },
  blog: { badge: "Insights", heading: "Insights & Guides", subheading: "Practical advice on home, lifestyle and property care in the northern suburbs of Copenhagen.", readMore: "Read more", backToBlog: "All articles", minRead: "min read", nav: "Insights" },
  card: { tagline: "VIP Home & Lifestyle Services", area: "Northern Suburbs of Copenhagen", call: "Call Us", email: "Email Us", save: "Save Contact", website: "Visit Website", scan: "Scan to open our website", nav: "Contact Card", whatsapp: "WhatsApp", sms: "Text Us" },
  careers: { badge: "Careers", nav: "Careers", heading: "Join WiCare", intro: "We are always looking for exceptional people who share our standards of discretion, precision, and care. We welcome unsolicited applications from talented professionals across home cleaning, private dining, and property care.", lookingTitle: "Who we look for", looking: ["Genuine pride in your craft and an eye for detail", "Discretion and absolute trustworthiness", "Reliability, punctuality, and professionalism", "Relevant experience and strong references"], howTitle: "How to apply", howIntro: "We read every application. To be considered, please be specific and include the following in your email:", items: ["The role or service you are applying for (Home Cleaning, Private Dining & Catering, or Property & Garden Care)", "Your CV, attached", "Your relevant experience and two references", "The languages you speak", "Whether you hold a valid driving licence", "Your earliest start date and weekly availability", "A short note: why WiCare, and what makes you exceptional"], applyCta: "Apply by Email", emailNote: "Applications are accepted by email only, at hello@wicare.vip.", emailSubject: "Application – [Your full name]", emailBody: "Hello WiCare,\n\nI would like to apply to join your team.\n\nRole / service of interest (Home Cleaning / Private Dining & Catering / Property & Garden Care):\nFull name:\nPhone:\nLanguages spoken:\nDriving licence (yes / no):\nYears of relevant experience:\nEarliest start date & weekly availability:\nTwo references (name + phone or email):\nWhy WiCare, and what makes you exceptional:\n\nI have attached my CV.\n\nKind regards," },
  servicePage: { included: "What's Included", whyChoose: "Why Choose", readyToBook: "Ready to Book?", callSchedulePre: "Call us to schedule your", callSchedulePost: "service.", backToServices: "Back to Services", alsoAvailable: "Also Available with Home Cleaning", alsoDesc: "While your home is being serviced, your WiCare team can handle these additional services, tailored to your agreement, never pre-bundled.", bookToday: "Book", bookTodayDesc: "All services are defined based on your agreement. Choose what you need, nothing is pre-bundled. Call us to schedule your", bookTodayDescEnd: "service. We respond within 2 business hours.", viewAll: "View all WiCare services" },
  serviceDetail: {
    "the-home": { name: "Home Cleaning", subtitle: "Home Cleaning", longDescription: "Home Cleaning provides VIP cleaning for private homes and businesses across the northern suburbs of Copenhagen. Every detail is handled with discretion, precision, and an uncompromising commitment to quality. Our teams are background-checked and trained to a white-glove standard.", features: ["Private residences & estates", "CEO-ready workspaces", "White-glove finish", "Smart product selection", "Background-checked staff", "Respectful of your home"], details: ["Discreet, professional service for discerning clients in the northern suburbs of Copenhagen", "Thoughtfully selected products balanced for safety and efficacy", "Flexible scheduling for mornings, evenings, weekends", "Dedicated team assigned to your property"] },
    "the-table": { name: "Private Dining & Catering", subtitle: "Private Dining & Catering", longDescription: "Private Dining & Catering is our flagship service. Our chef brings more than 13 years of experience, including Michelin-starred restaurants and the Danish Parliament, directly to your home or business. Whether it is an intimate dinner for two, a boardroom lunch, or a special celebration, every dish is prepared with precision, creativity, and genuine care. Menus are designed around your tastes and dietary needs.", features: ["Private chef dining", "Corporate catering", "Michelin pedigree", "Bespoke menus", "Wine pairing", "Event planning"], details: ["13+ years of Michelin-star and Danish Parliament experience", "Custom menu design for every occasion", "Ingredient sourcing from premium Danish purveyors", "Seamless setup, service, and cleanup"] },
    "the-estate": { name: "Property & Garden Care", subtitle: "Property & Garden Care", longDescription: "Property & Garden Care is your comprehensive solution for property and lifestyle needs. From expert landscaping and garden design to construction projects, handyman repairs, dog walking, and watering plants. Our skilled professionals deliver the same standard of excellence that defines every WiCare brand. One trusted partner handles it all.", features: ["Landscaping & gardening", "Construction projects", "Handyman services", "Property maintenance", "Dog walking", "Watering plants"], details: ["Vetted, licensed professionals for every service", "Full project management from concept to completion", "Watering and tending your plants", "Dog walking with photo updates", "Transparent, fixed-price quotes"] }
  },
  legal: {
    privacy: { title: "Privacy Policy", updated: "Last updated: June 2026", sections: [
      { h: "1. Information We Collect", p: "We collect only the information necessary to provide our services: your name, contact details, address, and any preferences you share when booking. We do not collect sensitive personal data unless you provide it voluntarily." },
      { h: "2. How We Use Your Information", p: "Your information is used solely to schedule and deliver services, communicate with you, and improve our offering. We never sell or rent your personal data to third parties." },
      { h: "3. Data Storage & Security", p: "Client information is stored securely and accessed only by authorised WiCare personnel. We apply appropriate technical and organisational measures to protect your data." },
      { h: "4. Sharing of Information", p: "We never share personal data without your explicit consent, except where required by law. Our team members are bound by strict confidentiality obligations." },
      { h: "5. Your Rights", p: "Under GDPR you have the right to access, correct, or delete your personal data, and to withdraw consent at any time. Contact us to exercise these rights." },
      { h: "6. Contact", p: "For any privacy questions, contact WiCare ApS (CVR-nummer: 46213270), Northern Suburbs of Copenhagen, Denmark. Phone: +45 52 72 11 02. Email: hello@wicare.vip." }
    ] },
    terms: { title: "Terms of Service", updated: "Last updated: June 2026", sections: [
      { h: "1. Booking & Confirmation", p: "All services are booked via telephone at +45 52 72 11 02. A booking is confirmed once WiCare ApS confirms availability. Services are subject to scheduler availability." },
      { h: "2. Pricing & Payment", p: "Prices are quoted per hour and may vary by service tier. Payment is due upon completion unless otherwise agreed in writing. WiCare ApS accepts bank transfer and major credit cards." },
      { h: "3. Cancellation Policy", p: "Cancellations made less than 24 hours before the scheduled appointment may incur a fee of 50% of the estimated service value. WiCare ApS reserves the right to cancel or reschedule due to unforeseen circumstances." },
      { h: "4. Valuables & Liability", p: "Clients are responsible for storing cash, jewellery, and other valuables in a safe, secured place before each visit. WiCare ApS is not liable for valuables left unsecured, for pre-existing damage, or for normal wear and tear. Responsibility for personal belongings remains with the client." },
      { h: "5. Privacy", p: "Client information is handled in accordance with our Privacy Policy. We never share personal data without explicit consent." },
      { h: "6. Amendments", p: "WiCare ApS reserves the right to amend these terms at any time. Clients will be notified of material changes." },
      { h: "Contact", p: "WiCare ApS (CVR-nummer: 46213270), Northern Suburbs of Copenhagen, Denmark. Phone: +45 52 72 11 02. Email: hello@wicare.vip." }
    ] }
  }
};
const da: typeof en = {
  nav: { services: "Services", whyWiCare: "Hvorfor WiCare", business: "Erhverv", testimonials: "Udtalelser", contact: "Kontakt", bookNow: "Book nu", getStarted: "Ring til os", callUs: "+45 52 72 11 02" },
  hero: { badge: "Nord for København", title: "VIP\nHjem & Livsstil\nServices", motto: "Diskretion. Præcision. Tillid.", subtitle: "Én betroet partner til alle aspekter af dit hjem, din livsstil og din virksomhed.\nVi udfører din vision med fejlfri præcision.", ctaConsultation: "Book et uforpligtende besøg", ctaServices: "Vores services", callCta: "Ring" },
  services: { sectionBadge: "Vores services", heading: "Hvad vi tilbyder", subheading: "Hver service defineres baseret på din aftale. Vælg hvad du har brug for, intet er forudbestemt.", flagship: "Flagskib", extendsNote: "Omfatter også bilpleje, garderobepleje, duftservice og rengøring af elektronik, alt defineret i din aftale.", learnMore: "Læs mere", bookAny: "Book en service", cards: [{ subtitle: "Hjemmerengøring", desc: "VIP rengøring til dit hjem og din arbejdsplads. White-glove service, omhyggeligt udvalgte produkter, fleksibel planlægning." }, { subtitle: "Privat madlavning & catering", desc: "Erfarne kokke til private middage, firmacatering og eksklusive events." }, { subtitle: "Ejendoms- & havepleje", desc: "Havearbejde, byggeri, handyman-service, hundeluftning og vanding af planter.\nÉn betroet partner til det hele." }] },
  whyUs: { badge: "Forskellen", heading: "Hvorfor kræsne kunder vælger WiCare", subheading: "Vi er ikke et rengøringsfirma. Vi er din betroede partner i at opretholde kvaliteten og elegancen i dit hjem eller kontor.", ctaBook: "Book en service", ctaCall: "Ring +45 52 72 11 02" },
  booking: { badge: "Book nu", heading: "Klar til at komme i gang?", subheading: "Ring til os i dag. Vi svarer inden for 2 arbejdstimer.", note: "Opbevar venligst kontanter, smykker og andre værdigenstande et sikkert sted inden din aftale.", or: "Eller skriv til os", whatsapp: "WhatsApp", email: "E-mail", stepsTitle: "Sådan foregår det", steps: [{ title: "Ring til os", desc: "Fortæl, hvad du har brug for – til dit hjem eller din virksomhed." }, { title: "Vi aftaler detaljerne", desc: "Omfang, tidspunkter og pris aftales med dig. Ingen faste pakker." }, { title: "Dit faste team", desc: "Det samme diskrete og punktlige team fra første besøg." }] },
  contact: { badge: "Kontakt", heading: "Kom i kontakt", intro: "Vi vil gerne høre fra dig", introDesc: "Vores team svarer på alle henvendelser inden for 2 arbejdstimer.", phoneLabel: "Telefon", emailLabel: "Email", locationLabel: "Serviceområde", location: "Københavns nordlige forstæder", ctaCall: "Ring nu", ctaEmail: "Send e-mail", directTitle: "Ring direkte til os", directDesc: "Vores team er klar til at hjælpe. Ingen formularer, ingen ventetid, bare en samtale.", directAvailability: "Tilgængelig 5 dage om ugen. Svar inden for 2 timer" },
  areasMap: { badge: "Områder", heading: "Hvor vi arbejder", lede: "Københavns nordlige forstæder, fra Hellerup til Hørsholm. For private hjem og virksomheder.", note: "Illustrativt kort", mapLabel: "Kort over de områder, WiCare betjener nord for København", south: "København" },
  footer: { tagline: "VIP livsstilsservices til private boliger og professionelle miljøer i Københavns nordlige forstæder.", navTitle: "Navigation", contactTitle: "Kontakt", quickLinksTitle: "Hurtige links", legalTitle: "Juridisk", bookNow: "Book nu", areasTitle: "Områder vi betjener", areas: "Hellerup · Charlottenlund · Klampenborg · Gentofte · Rudersdal\nHørsholm · Rungsted · Vedbæk · Skodsborg · Nordsjælland", cvr: "CVR-nummer: 46213270", copyright: "© 2026 WiCare ApS. Alle rettigheder forbeholdes.", privacy: "Privatlivspolitik", terms: "Servicevilkår", links: [{ label: "Services", href: "/#services" }, { label: "Hvorfor WiCare", href: "/#trust" }, { label: "Udtalelser", href: "/#testimonials" }, { label: "Book", href: "/#book" }, { label: "Kontakt", href: "/#book" }] },
  floating: { bookNow: "Book nu", ariaLabel: "Ring til WiCare", whatsappAria: "Skriv på WhatsApp", whatsappMsg: "Hej WiCare, jeg vil gerne høre om jeres services." },
  notFound: { title: "Siden blev ikke fundet", desc: "Beklager, siden du leder efter findes ikke eller er flyttet.", home: "Tilbage til forsiden" },
  consent: { text: "Vi bruger cookies til at måle trafik og forbedre din oplevelse. Du kan acceptere eller afvise ikke-nødvendige cookies.", accept: "Acceptér", decline: "Afvis", privacy: "Privatlivspolitik" },
  faq: { badge: "FAQ", nav: "FAQ", heading: "Ofte stillede spørgsmål", intro: "Svar på almindelige spørgsmål om WiCares VIP hjem- og livsstilsservices i Københavns nordlige forstæder.", items: [
    { q: "Hvilke områder dækker I?", a: "Vi betjener private hjem og virksomheder i Københavns nordlige forstæder – Gentofte (Hellerup, Skovshoved, Charlottenlund, Ordrup, Klampenborg, Jægersborg), Lyngby-Taarbæk (Kongens Lyngby, Sorgenfri, Virum, Taarbæk), Rudersdal (Holte, Søllerød, Nærum, Skodsborg, Vedbæk, Birkerød), Hørsholm, Rungsted og Allerød." },
    { q: "Hvilke services tilbyder I?", a: "Tre: hjemmerengøring, privat madlavning & catering samt ejendoms- & havepleje — hver tilpasset din aftale, aldrig forudbestemt." },
    { q: "Er jeres personale screenet og baggrundstjekket?", a: "Ja. Hvert teammedlem er baggrundstjekket, trænet til white-glove-standard og forpligtet til diskretion og fortrolighed." },
    { q: "Hvordan får jeg et tilbud eller booker?", a: "Ring til os på +45 52 72 11 02 – eller skriv på WhatsApp eller e-mail. Vi svarer inden for to arbejdstimer, og vi aftaler altid omfang og pris med dig, før vi går i gang." },
    { q: "Tilbyder I både faste og enkeltstående opgaver?", a: "Begge dele. Vi arrangerer faste planer eller enkelte besøg, defineret ud fra dine behov." },
    { q: "Hvordan håndterer I nøgler, privatliv og værdigenstande?", a: "Vi håndterer nøgler og adgang sikkert og behandler dit hjem med diskretion. Vi beder dig opbevare kontanter, smykker og værdigenstande inden hvert besøg." },
    { q: "Hvad er jeres åbningstider?", a: "Mandag til fredag, 08:00–18:00, med fleksibel planlægning til morgener, aftener og weekender efter aftale." },
  ] },
  blog: { badge: "Indsigt", heading: "Indsigt & Guides", subheading: "Praktiske råd om hjem, livsstil og ejendomspleje i Københavns nordlige forstæder.", readMore: "Læs mere", backToBlog: "Alle artikler", minRead: "min læsning", nav: "Indsigt" },
  card: { tagline: "VIP hjem- & livsstilsservices", area: "Københavns nordlige forstæder", call: "Ring til os", email: "Send e-mail", save: "Gem kontakt", website: "Besøg hjemmesiden", scan: "Scan for at åbne vores hjemmeside", nav: "Kontaktkort", whatsapp: "WhatsApp", sms: "Send SMS" },
  careers: { badge: "Karriere", nav: "Karriere", heading: "Bliv en del af WiCare", intro: "Vi søger altid exceptionelle mennesker, der deler vores standarder for diskretion, præcision og omhu. Vi modtager gerne uopfordrede ansøgninger fra dygtige fagfolk inden for hjemmerengøring, privat madlavning og ejendomspleje.", lookingTitle: "Hvem vi søger", looking: ["Ægte stolthed over dit håndværk og sans for detaljen", "Diskretion og absolut troværdighed", "Pålidelighed, punktlighed og professionalisme", "Relevant erfaring og stærke referencer"], howTitle: "Sådan ansøger du", howIntro: "Vi læser hver ansøgning. For at komme i betragtning bedes du være konkret og inkludere følgende i din email:", items: ["Den rolle eller service du søger (hjemmerengøring, privat madlavning & catering eller ejendoms- & havepleje)", "Dit CV, vedhæftet", "Din relevante erfaring og to referencer", "De sprog du taler", "Om du har et gyldigt kørekort", "Din tidligste startdato og ugentlige tilgængelighed", "En kort note: hvorfor WiCare, og hvad gør dig exceptionel"], applyCta: "Ansøg via e-mail", emailNote: "Ansøgninger modtages kun via email på hello@wicare.vip.", emailSubject: "Ansøgning – [Dit fulde navn]", emailBody: "Hej WiCare,\n\nJeg vil gerne ansøge om at blive en del af jeres team.\n\nRolle / service af interesse (hjemmerengøring / privat madlavning & catering / ejendoms- & havepleje):\nFulde navn:\nTelefon:\nSprog jeg taler:\nKørekort (ja / nej):\nÅrs relevant erfaring:\nTidligste startdato & ugentlige tilgængelighed:\nTo referencer (navn + telefon eller email):\nHvorfor WiCare, og hvad gør dig exceptionel:\n\nJeg har vedhæftet mit CV.\n\nVenlig hilsen," },
  servicePage: { included: "Hvad er inkluderet", whyChoose: "Hvorfor vælge", readyToBook: "Klar til at booke?", callSchedulePre: "Ring til os for at planlægge din", callSchedulePost: "service.", backToServices: "Tilbage til services", alsoAvailable: "Også muligt sammen med hjemmerengøring", alsoDesc: "Mens dit hjem bliver serviceret, kan dit WiCare-team håndtere disse ekstra services, skræddersyet til din aftale, aldrig forudbestemt.", bookToday: "Book", bookTodayDesc: "Alle services defineres baseret på din aftale. Vælg hvad du har brug for, intet er forudbestemt. Ring til os for at planlægge din", bookTodayDescEnd: "service. Vi svarer inden for 2 arbejdstimer.", viewAll: "Se alle WiCare services" },
  serviceDetail: {
    "the-home": { name: "Hjemmerengøring", subtitle: "Hjemmerengøring", longDescription: "Hjemmerengøring er VIP-rengøring til private hjem og virksomheder i Københavns nordlige forstæder. Hver detalje håndteres med diskretion, præcision og en kompromisløs forpligtelse til kvalitet. Vores teams er baggrundstjekkede og trænet til en white-glove standard.", features: ["Private boliger & ejendomme", "Direktørklare arbejdspladser", "White-glove finish", "Smart produktvalg", "Baggrundstjekket personale", "Respekt for dit hjem"], details: ["Diskret, professionel service for kræsne kunder i Københavns nordlige forstæder", "Omhyggeligt udvalgte produkter balanceret for sikkerhed og effektivitet", "Fleksibel planlægning til morgener, aftener og weekender", "Dedikeret team tildelt din ejendom"] },
    "the-table": { name: "Privat madlavning & catering", subtitle: "Privat madlavning & catering", longDescription: "Privat madlavning & catering er vores flagskib. Vores kok har mere end 13 års erfaring, blandt andet fra Michelin-restauranter og Folketinget, og kommer direkte hjem til dig eller din virksomhed. Uanset om det er en intim middag for to, en frokost i bestyrelseslokalet eller en særlig fejring, tilberedes hver ret med præcision, kreativitet og ægte omhu. Menuer designes ud fra din smag og dine kostbehov.", features: ["Privat kokmiddag", "Erhvervscatering", "Michelin-baggrund", "Skræddersyede menuer", "Vinmenu", "Eventplanlægning"], details: ["13+ års erfaring fra Michelin-restauranter og Folketinget", "Skræddersyet menudesign til enhver lejlighed", "Råvarer fra førende danske leverandører", "Problemfri opdækning, servering og oprydning"] },
    "the-estate": { name: "Ejendoms- & havepleje", subtitle: "Ejendoms- & havepleje", longDescription: "Ejendoms- & havepleje er din samlede løsning til ejendoms- og livsstilsbehov. Fra ekspert-landskabspleje og havedesign til byggeprojekter, handyman-reparationer, hundeluftning og vanding af planter. Vores dygtige fagfolk leverer den samme høje standard, der definerer alle WiCare-brands. Én betroet partner klarer det hele.", features: ["Landskabspleje & havearbejde", "Byggeprojekter", "Handyman-service", "Ejendomsvedligeholdelse", "Hundeluftning", "Vanding af planter"], details: ["Godkendte, autoriserede fagfolk til hver service", "Fuld projektledelse fra idé til færdiggørelse", "Vanding og pasning af planter", "Hundeluftning med fotoopdateringer", "Gennemsigtige tilbud til fast pris"] }
  },
  legal: {
    privacy: { title: "Privatlivspolitik", updated: "Senest opdateret: juni 2026", sections: [
      { h: "1. Oplysninger vi indsamler", p: "Vi indsamler kun de oplysninger, der er nødvendige for at levere vores services: dit navn, kontaktoplysninger, adresse og eventuelle præferencer, du deler ved booking. Vi indsamler ikke følsomme personoplysninger, medmindre du afgiver dem frivilligt." },
      { h: "2. Hvordan vi bruger dine oplysninger", p: "Dine oplysninger bruges udelukkende til at planlægge og levere services, kommunikere med dig og forbedre vores tilbud. Vi sælger eller udlejer aldrig dine personoplysninger til tredjeparter." },
      { h: "3. Datalagring & sikkerhed", p: "Kundeoplysninger opbevares sikkert og tilgås kun af autoriseret WiCare-personale. Vi anvender passende tekniske og organisatoriske foranstaltninger for at beskytte dine data." },
      { h: "4. Deling af oplysninger", p: "Vi deler aldrig personoplysninger uden dit udtrykkelige samtykke, undtagen hvor loven kræver det. Vores medarbejdere er bundet af strenge fortrolighedsforpligtelser." },
      { h: "5. Dine rettigheder", p: "I henhold til GDPR har du ret til at få adgang til, rette eller slette dine personoplysninger og til at trække dit samtykke tilbage til enhver tid. Kontakt os for at udøve disse rettigheder." },
      { h: "6. Kontakt", p: "For spørgsmål om privatliv, kontakt WiCare ApS (CVR-nummer: 46213270), Københavns nordlige forstæder, Danmark. Telefon: +45 52 72 11 02. Email: hello@wicare.vip." }
    ] },
    terms: { title: "Servicevilkår", updated: "Senest opdateret: juni 2026", sections: [
      { h: "1. Booking & bekræftelse", p: "Alle services bookes telefonisk på +45 52 72 11 02. En booking bekræftes, når WiCare ApS bekræfter tilgængelighed. Services er underlagt planlæggerens tilgængelighed." },
      { h: "2. Priser & betaling", p: "Priser oplyses pr. time og kan variere efter serviceniveau. Betaling forfalder ved færdiggørelse, medmindre andet er skriftligt aftalt. WiCare ApS accepterer bankoverførsel og større kreditkort." },
      { h: "3. Afbestillingspolitik", p: "Afbestillinger foretaget mindre end 24 timer før den planlagte aftale kan medføre et gebyr på 50% af den anslåede serviceværdi. WiCare ApS forbeholder sig retten til at aflyse eller omlægge på grund af uforudsete omstændigheder." },
      { h: "4. Værdigenstande & ansvar", p: "Kunder er ansvarlige for at opbevare kontanter, smykker og andre værdigenstande på et sikkert, aflåst sted inden hvert besøg. WiCare ApS er ikke ansvarlig for værdigenstande, der efterlades usikrede, for eksisterende skader eller for almindeligt slid. Ansvaret for personlige ejendele forbliver hos kunden." },
      { h: "5. Privatliv", p: "Kundeoplysninger håndteres i overensstemmelse med vores Privatlivspolitik. Vi deler aldrig personoplysninger uden udtrykkeligt samtykke." },
      { h: "6. Ændringer", p: "WiCare ApS forbeholder sig retten til at ændre disse vilkår til enhver tid. Kunder vil blive underrettet om væsentlige ændringer." },
      { h: "Kontakt", p: "WiCare ApS (CVR-nummer: 46213270), Københavns nordlige forstæder, Danmark. Telefon: +45 52 72 11 02. Email: hello@wicare.vip." }
    ] }
  }
};
export const translations = { en, da };
